"""Second migration

Revision ID: 9018f1585e5f
Revises: 
Create Date: 2020-07-04 14:06:45.832000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9018f1585e5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_and_other_readings', sa.Column('picture_link', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books_and_other_readings', 'picture_link')
    # ### end Alembic commands ###
